usr/bin/vala-0.24
usr/bin/valac-0.24
usr/bin/vala-gen-introspect-0.24
usr/bin/vapigen-0.24
usr/bin/vapicheck-0.24
usr/share/man/man1/valac-0.24.1
usr/share/man/man1/vapigen-0.24.1
usr/share/man/man1/vala-gen-introspect-0.24.1
usr/share/pkgconfig/vapigen-0.24.pc
usr/lib/*/vala-0.24/gen-introspect-0.24
vala.m4 /usr/share/vala-0.24/
vapigen/vapigen.m4 /usr/share/vala-0.24/
vapigen/Makefile.vapigen /usr/share/vala-0.24/
